### ISSUE TITLE
Can I continue this project for GSoC 2017

### ISSUE THREAD

**Issue by thetransformerr** [Visaoni/beagle-sonic-anemometer#2]
I wish to take this project to its intended goal of being a portable device to measure wind speed almost as comparable to standard devices, any help regarding current status on this project if you had been working on it recently and what I must do from your past experience

**Comment by Visaoni** [comment]
I've been meaning to write something up generally about my thoughts on it. I won't go into the status of everything now, but I'm happy to share my thoughts about continuing the project here.

First off, no, I haven't worked on this any more.

Secondly, the main issue, at least in the large, is having a solid idea of when a pulse is actually sent. I rather naively started this with the assumption that would be a trivial issue, but as far as I came to understand it, it's not. If you look at some ultrasonic transmitter schematics you'll see they seem to use a hardware oscillator and then have a way for a signal to allow the oscillator output to pass through to the transmitter. If you take the signal as the send time, you add enough uncertainty that you'll have a hard time distinguishing no wind from a hurricane (roughly, I don't recall the exact numbers).

There are couple other DIY sonic anemometer projects out there that I found, but they were either all analog or using a microcontroller just as a timer, and doing everything else (pulse transmission and detection) on the analog side.  I think the reason for this is mostly a result of the above issue.

So, my suggestion would be to only try to take on this project if you have an idea of how to solve that problem. If you do figure out how to do it, I'd love to hear it.

**Comment by thetransformerr** [comment]
thanks for sharing your knowledge,I have submitted my proposal, as here http://elinux.org/GSoC2017_sonic_anemometer_proposal , I have changed a bit the way of calculation then your project, but the pulse transmission and receiving would be the main challenge here and you are a bit late in pointing out gravity of this issue.

So I don't have solid work plan to solve this issue, but I think in this problem, the main challenge would be transmission time record, as receive of pulse can be detected by analysing waveform and analysing of waveform can be a potential solution if we use a free flow transducers i.e working without triggers.

I would find solution quickly but I think it is going to be some innovation thing.

**Comment by Visaoni** [comment]
I suspect you'll probably have better luck avoiding the issue altogether and not using a basic time of flight measurement. I see you're already looking at using the phase difference. I never did look very deeply into that as time-of-flight seemed a lot more direct, but if it can get you out of needing to know the exact transmission time then it's probably your best bet.

**Comment by thetransformerr** [comment]
and did you tried to get inside the working used by commercial anemometer?They seem to be extremely portable and compact, hence there may be way of avoiding oscillator and use DAC instead....

**Comment by Visaoni** [comment]
I did not. By the time I was really seeing the problem it was pretty late and I had a number of other outstanding issues that needed to be dealt with first anyway so I never really got around to trying to properly tackle it. You might well be able to just use a DAC. I don't recall any particular reason that wouldn't work. I'm guessing I just didn't look into it due to time issues.

**Comment by Visaoni** [comment]
One thing to watch for is the pin usage. Those things are valuable and get sucked up pretty fast. Make sure you have enough pins available that are capable of what you need for working with whatever DAC you're considering.

**Comment by thetransformerr** [comment]
thanks for your suggestions, I think I can expect your help later also, would you please share some other method to reach you....
